api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from api import viewsets

app_name = 'api'

router = SimpleRouter()
router.register('users', viewsets.UserViewSet, basename='users')
router.register('brands', viewsets.BrandViewSet, basename='brands')
router.register('automodels', viewsets.AutoModelViewSet, basename='automodel')
router.register('vehicles', viewsets.VehicleViewSet, basename='vehicles')
router.register('services', viewsets.ServiceViewSet, basename='services')
router.register('maintenance', viewsets.MaintenanceViewSet, basename='maintenance')

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('app/', include('app.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('', views.login_user, name='login_user'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/maintenance/new', views.dashboard_maintenance_new, name='dashboard_maintenance_new'),
    path('dashboard/maintenance/<id>/edit', views.dashboard_maintenance_edit, name='dashboard_maintenance_edit'),
]

users/forms/login_form.py
from django import forms

from utils.django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Type your username')
        add_placeholder(self.fields['password'], 'Type your password')

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

users/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from utils.django_forms import add_placeholder, strong_password


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Your username')
        add_placeholder(self.fields['email'], 'Your e-mail')
        add_placeholder(self.fields['first_name'], 'Your first name')
        add_placeholder(self.fields['last_name'], 'Your last name')

    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Your password'}),
        error_messages={'required': 'Password must not be empty'},
        help_text=(
            'Password must have at least one uppercase letter, '
            'one lowercase letter and one number. The length should be '
            'at least 8 characters.'),
        validators=[strong_password]
    )
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Repeat your password'}),
        label='Repeat your password',
    )
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        )
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'username': 'Username',
            'email': 'E-mail',
            'password': 'Password',
        }
        help_texts = {
            'email': 'The e-mail must be valid.',
        }
        error_messages = {
            'username': {'required': 'This field must not be empty', }
        }

    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError('Passwords must be equal', code='invalid')
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': [
                    password_confirmation_error,
                ],
            })

base_templates/templates/app/pages/content_view.html
{% extends 'global/base.html' %}

{% block title %} | {{ content.vehicle }}{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'templates/app/partials/content.html' %}
</diV>
{% endblock content %}

base_templates/templates/app/pages/dashboard.html
{% extends 'global/base.html' %}

{% block title %}Dashboard - {{ request.user }}{% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Dashboard - {{ request.user }}</h2>
        <a class="plaintext-button" href="{% url 'users:dashboard_maintenance_new' %}">add maintenance</a>
        {% include 'templates/app/partials/login_message.html' %}
        <div class="dashboard-container">
            <h3>Your Maintenances</h3>
            <ul>
                {% for data in data %}
                    <a href="{% url 'users:dashboard_maintenance_edit' data.id%}">{{ data.vehicle }}</a><br><br>
                {% empty %}
                    <li>
                        <p>You don't have any maintenance registered, register one.</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% include 'templates/app/partials/messages.html' %}
{% endblock content %}

base_templates/templates/app/pages/dashboard_maintenance.html
{% extends 'global/base.html' %}

{% block title %}|Dashboard Maintenance {{ data.id }}{% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Dashboard Maintenance {{ data.id }}</h2>
        <a class="plaintext-button" href="{% url 'users:dashboard' %}">return to dashboard</a>
        {% include 'templates/app/partials/messages.html' %}
        {% include 'templates/app/partials/login_message.html' %}
        <div class="left">
            {% include 'templates/app/partials/form.html' %}
        </div>
    </div>
{% endblock content %}

base_templates/templates/app/pages/home.html
{% extends 'global/base.html' %}

{% block title %} | Home {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for content in contents %}
        {% include 'templates/app/partials/content.html' %}
    {% empty %}
        <div class="margin">
            <h1>Didn't find here!</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

base_templates/templates/app/pages/login.html
{% extends 'global/base.html' %}

{% block title %}{% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Login</h2>
        <p><a class="plaintext-button" href="{% url 'users:register' %}">Click here</a> to register a new user</p>
        {% include 'templates/app/partials/login_message.html' %}
    </div>
    {% include 'templates/app/partials/messages.html' %}
    {% if not user.is_authenticated %}
        {% include 'templates/app/partials/form.html' %}
    {% endif %}
{% endblock content %}

base_templates/templates/app/pages/register.html
{% extends 'global/base.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Register</h2>
        <p>Click <a class="plaintext-button" href="{% url 'users:login_user' %}">here</a> to log in.</p>
    </div>
    {% include 'templates/app/partials/messages.html' %}
    {% include 'templates/app/partials/form.html' %}
{% endblock content %}