api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from api import viewsets

app_name = 'api'

router = SimpleRouter()
router.register('users', viewsets.UserViewSet, basename='users')
router.register('brands', viewsets.BrandViewSet, basename='brands')
router.register('automodels', viewsets.AutoModelViewSet, basename='automodel')
router.register('vehicles', viewsets.VehicleViewSet, basename='vehicles')
router.register('services', viewsets.ServiceViewSet, basename='services')
router.register('maintenance', viewsets.MaintenanceViewSet, basename='maintenance')

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('maintenance/<int:id>/', views.content, name='content'),
    path('send-email/<int:id>/', views.send_email, name='send_email'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('app/', include('app.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('', views.login_user, name='login_user'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/maintenance/new', views.dashboard_maintenance_new, name='dashboard_maintenance_new'),
    path('dashboard/maintenance/<id>/edit', views.dashboard_maintenance_edit, name='dashboard_maintenance_edit'),
]

base_templates/templates/app/partials/content.html
<div class="content content-list-item">
    <div class="content-title-container">
        {% if is_detail_view is not True %}
            <div class="content-title-container">
                <h2 class="content-title">
                    <a href="{% url 'app:content' content.id%}">{{ content.vehicle }}</a>
                </h2>
            </div>
        {% endif %}
    </div>
    {% if is_detail_view is not True %}
        <footer class="content-footer">
            <a class="content-read-more button button-dark button-full-width" href="{% url 'app:content' content.id %}">
                <i class="fas fa-eye"></i>
                <span>See more...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_detail_view is True %}
        <div class="main-information">
            <ul>
                <li>Owner: {{ content.owner }}</li>
                <li>Vehicle: {{ content.vehicle }}</li>
                <li>Kilometer: {{ content.km_vehicle }}</li>
                <li>Date: {{ content.date }}</li>
                <li>Next date:{{ content.next_date }}</li>
                <li>Services value: {{ content.full_value }}</li>
            </ul>
        </div>
        <div class="main-content padding">
            <a class="content-list back" href="{% url 'app:home' %}"><i class="fas fa-backward"></i> return</a>
        </div> 
        <div class="main-content padding_2">
            <a class="content-list back" href="{% url 'app:send_email' content.id%}"> Send e-mail</a>
        </div>
    {% endif %}
</div>

base_templates/templates/app/partials/footer.html
<footer class="main-footer">
    <div>
        <a href="https://github.com/FelipeTreis/extension_work">GitHub</a>
    </div>
    <div>
        <a href="https://unifil.br/" target="_blank" rel="noreferrer noopener">UniFil Project</a>
    </div>
    <div>
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

base_templates/templates/app/partials/form.html
<div class="main-content container">
    <form action="{{ form_action }}" method="POST">
        {% csrf_token %}
        <div class="form-content form-content-grid">
            {% for field in form %}
                <div class="form-group {{ field.field.widget.attrs.class }}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    {% if field.help_text %}
                        <p class="help-text">{{ help_text }}</p>
                    {% endif %}
                    {{ field.errors }}
                </div>
            {% endfor %}
        </div>
        <div class="form-content form-content-grid">
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </div>
    </form>
</div>

base_templates/templates/app/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="icon" type="image/x-icon" href="{% static 'global/img/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'global/css/styles.css' %}">

base_templates/templates/app/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1 class="main-logo">
            <span class="main-logo-text"><i class="fas fa-car"></i></i> My Maintenance</span>
        </h1>
    </div>
</header>

base_templates/templates/app/partials/login_message.html
{% if request.user.is_authenticated %}
    <div class="login-message">
        You are logged with {{ request.user.username }}
        <form class="inline-form" action="{% url 'users:logout' %}" method="POST">
            {% csrf_token %}
            <input type="hidden", name="username" value="{{ request.user.username }}">
            <button class="plaintext-button" type="submit">click here</button>
        </form> to logout.
    </div><br>
    <div>
        <h2><a class="plaintext-button" href="{% url 'app:home' %}">Maintenance Information</a></h2>
    </div>
{% endif %}

base_templates/templates/app/partials/menu.html
<button class="button-show-menu button-show-menu-visible">
    <i class="fas fa-bars"></i>
    <span class="hidden-text">Show menu</span>
  </button>
  
  <div class="menu-container menu-hidden">
    <button class="button-close-menu button-close-menu-visible">
      <i class="fas fa-times-circle"></i>
      <span class="hidden-text">Close menu</span>
    </button>
  
    <div class="menu-content">
      <nav class="menu-nav">        
        <a href="{% url 'users:login_user' %}">Home</a>
        <a href="{% url 'app:home' %}">Maintenances</a>
        <a href="{% url 'users:register' %}">New User</a>
        <a href="{% url 'users:dashboard_maintenance_new' %}">New maintenance</a>
        <a href="">About Us</a>
      </nav>
    </div>
  </div>

base_templates/templates/app/partials/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}