api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from api import viewsets

app_name = 'api'

router = SimpleRouter()
router.register('users', viewsets.UserViewSet, basename='users')
router.register('brands', viewsets.BrandViewSet, basename='brands')
router.register('automodels', viewsets.AutoModelViewSet, basename='automodel')
router.register('vehicles', viewsets.VehicleViewSet, basename='vehicles')
router.register('services', viewsets.ServiceViewSet, basename='services')
router.register('maintenance', viewsets.MaintenanceViewSet, basename='maintenance')

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

app/web/urls.py
from django.urls import path

from app.web import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    path('maintenance/<int:id>/', views.content, name='content'),
    path('send-email/<int:id>/', views.send_email, name='send_email')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('app/', include('app.urls')),
    path('', include('users.urls')),
]

app/templates/app/partials/content.html
<div class="content content-list-item">
    <div class="content-title-container">
        {% if is_detail_view is not True %}
            <div class="main-content">
                <a class="content-list" href="{% url 'web:content' content.id%}">{{ content.vehicle }}</a>
            </div>
        {% endif %}
    </div>
    {% if is_detail_view is True %}
        <div class="main-content-text">
            <ul>
                <li>Owner: {{ content.owner }}</li>
                <li>Vehicle: {{ content.vehicle }}</li>
                <li>Kilometer: {{ content.km_vehicle }}</li>
                <li>Date: {{ content.date }}</li>
                <li>Next date:{{ content.next_date }}</li>
                <li>Services value: {{ content.full_value }}</li>
            </ul>
        </div>
        <div class="main-content">
            <a class="content-list" href="{% url 'web:home' %}"><i class="fas fa-backward"></i> back home</a>
        </div>
    {% endif %}
</div>